### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Chryma** [lejeffe/MonsterHP#1]
Seems like the plugin isn't working anymore, would also be nice if you could make it show the HP value instead of the percentage if possible!

https://i.imgur.com/zaBmGB9.png

**Comment by fuzxi** [comment]
It mostly works for me, but the HP value disappears completely at certain camera angles.

**Comment by lejeffe** [comment]
> 

Could you post a screenshot or share the area/npc's this happens on?

**Comment by lejeffe** [comment]
> 

All of these things should be fixed/added with the last update

**Comment by fuzxi** [comment]
> > It mostly works for me, but the HP value disappears completely at certain camera angles.
> 
> Could you post a screenshot or share the area/npc's this happens on?

Infernal mages in the Slayer Tower, generally while facing northward.

**Comment by Anonymous75** [comment]
> > It mostly works for me, but the HP value disappears completely at certain camera angles.
> 
> Could you post a screenshot or share the area/npc's this happens on?

I have the same issue. The HP values disappear from everything on screen when I lower my camera too far. They only display normally when the camera is raised above a certain angle. I was testing it at the Goblins, east of Lumbridge.
