### ISSUE TITLE
Would love this same plugin but for HP Value instead of HP %

### ISSUE THREAD

**Issue by Puzzle-Drops** [lejeffe/MonsterHP#15]
HP % works great for a lot of scenarios but for some the HP value would work better. For example on Zuk. There are thresholds like at 480 Jad Spawns and at 240 Healers spawn. I would like to have the Zuk HP value shown instead of HP %. Could be a separate plugin.

**Comment by Skipperia** [comment]
I wanted that too, I added it myself and created a pull request
I don't code much in Java but I think its good enough

**Comment by Skipperia** [comment]
> HP % works great for a lot of scenarios but for some the HP value would work better. For example on Zuk. There are thresholds like at 480 Jad Spawns and at 240 Healers spawn. I would like to have the Zuk HP value shown instead of HP %. Could be a separate plugin.

I wanted that too, I added it myself and created a pull request
I don't code much in Java but I think its good enough
