### ISSUE TITLE
Ability to assign different color to lowest HP NPC

### ISSUE THREAD

**Issue by Z7-z** [lejeffe/MonsterHP#21]
Currently it displays all NPC HPs in the same color it would be very nice if you could display a different color (preferably user chosen) for the lowest HP it can find when you right click so it’s much easier to distinguish which NPC has the lowest hp every time

**Comment by lejeffe** [comment]
Seems a pretty niche option. unless you want to write a merge i won't spend time making this. Soon i will have an option that hides all the 100% monster. This should help.

**Comment by Z7-z** [comment]
Thank you for the quick response
