### ISSUE TITLE
Boss percentage on monster doesn't change based on actual HP

### ISSUE THREAD

**Issue by toenailrs** [lejeffe/MonsterHP#26]
Any reason the HP percentage above baba is 100 and not reading like it should in the top bar? https://i.imgur.com/rMMrrjp.png
happened with all toa bosses
This plugin enabled the 100 over his head. But its not lining up with the % in the HP bar on the top of the screen. https://i.imgur.com/aDWO9uO.png

Wasn't like this yesterday but today it is.
Only thing I touched since yesterday was added the highlighted words in the NPC names box. https://i.imgur.com/Yi7juil.png

**Comment by daleric-xyz** [comment]
> Any reason the HP percentage above baba is 100 and not reading like it should in the top bar? https://i.imgur.com/rMMrrjp.png happened with all toa bosses This plugin enabled the 100 over his head. But its not lining up with the % in the HP bar on the top of the screen. https://i.imgur.com/aDWO9uO.png
> 
> Wasn't like this yesterday but today it is. Only thing I touched since yesterday was added the highlighted words in the NPC names box. https://i.imgur.com/Yi7juil.png

did you ever fix this? I'm getting it in TOA and TOB - they're just staying at 100.

**Comment by toenailrs** [comment]
> > Any reason the HP percentage above baba is 100 and not reading like it should in the top bar? https://i.imgur.com/rMMrrjp.png happened with all toa bosses This plugin enabled the 100 over his head. But its not lining up with the % in the HP bar on the top of the screen. https://i.imgur.com/aDWO9uO.png
> > Wasn't like this yesterday but today it is. Only thing I touched since yesterday was added the highlighted words in the NPC names box. https://i.imgur.com/Yi7juil.png
> 
> did you ever fix this? I'm getting it in TOA and TOB - they're just staying at 100.

It has been fixed but I really don't know how so. I'm sorry :(
