### ISSUE TITLE
Disable anti-aliasing for small custom fonts

### ISSUE THREAD

**Issue by logarrhythmic** [lejeffe/MonsterHP#27]
I want to have the overlay font size really small, but anti-aliasing is always turned on for custom fonts currently. Looking at the code, anti-aliasing is turned off if a custom font is not used. There are really small pixel fonts that I would like to use without antialiasing, like [Teeny Tiny Pixls](https://www.fontspace.com/teeny-tiny-pixls-font-f30095), only 5 pixels high compared to the 12 pixels of the "Small" default font and still readable. There's also a 3x3 font I found, which is not enough to fully render numbers, but the vague shapes would still technically work.

I think there are two ways this could be improved: you could either
- Add an anti-aliasing checkbox in the font section of the config and use that (should still be forced off if not using custom font)
or
- Turn off anti-aliasing for font sizes of... maybe 6 or lower? Worse option IMO but only needs a single line changed (MonsterHPOverlay.java:49)

**Comment by lejeffe** [comment]
As far as i can see now, the AA is only use on the default runescape font. This shouldn't be enabled on others. Correct me if wrong

**Comment by logarrhythmic** [comment]
![image](https://github.com/lejeffe/MonsterHP/assets/1952758/a50b1f9c-77da-480d-92fb-823173be9d9a)
Custom font off on the left, on (roboto) on the right, 16px

**Comment by logarrhythmic** [comment]
I think it might depend on the font since it's not explicitly set, Courier doesn't get anti-aliased for me.
