### ISSUE TITLE
SUGGESTION: Able to hide monsters that are full health/have only show monsters that you/someone else is in combat with OR hide unattackble NPC's

### ISSUE THREAD

**Issue by santzuu** [lejeffe/MonsterHP#28]
Any of the options in the title would make imo the plugin 100 times better.

At the "show all" option is kinda nice since its such a drag to write each NPC name seperately... But the problem is that then it literally highlights EVERYTHING. I feel its kinda silly that it shows all unattackble npc's and all hunter npc's health as 100 as well... Would be nice to have some options to remove that clutter my ideas would be:

1) Just hide all unattackble npc's by default (thers 0 need to see those? since you cant even attack them)
2) Have a blacklist for npc's which health you dont want to see IF you have the "show all" option toggled (I assume this should be possible to be coded since the plugin already has a whitelist for npc's?)
3) have some right click option to show the health for some npc if its not already shown or vice versa hide it if its shown
4) have the health be drawn ONLY when said monster is in combat with you or if thats not possible when its in combat with anyone
5) similar to what was suggested already - hide the HP when monster has 100% health and then show it ONLY when said monster is missing health

thanks for the amazing module and hopefully youd be able to implement any of these options and potentially even multiple ones since any of those would make it funtion way better!

**Comment by Jin-Jiyunsun** [comment]
+1

**Comment by lejeffe** [comment]
have a pull request for this
