### ISSUE TITLE
Wrong HP percentage

### ISSUE THREAD

**Issue by LetterToLuma** [lejeffe/MonsterHP#33]
The HP percentage is off by a few decimals and always tricks me into thinking i got into the boulder phase at baba.

for example HP bar shows 66.1% however monster hp percentage shows 65.9% health.

a fix would be awesome, thanks

**Comment by thejdubs** [comment]
unless the way the hp is being obtained has changed, this is an issue with having to use the hp bar as the health indictor instead of the actual health value.
discussed a bit here
https://github.com/lejeffe/MonsterHP/pull/12

**Comment by lejeffe** [comment]
Depending on the size/resolution that jagex uses for we only have access to a certain accuracy. often hp bar available to me is something like 36 positions. this would equite to having a accuracy of around 3hp. Not much i can change to remedy this.
