### ISSUE TITLE
Numeric health broken at certain bosses. 

### ISSUE THREAD

**Issue by NuclearRalph** [lejeffe/MonsterHP#34]
As seen in image below, numeric health does not appear to work on certain bosses. It works on random mobs like cows and abyssal leaches etc. Quite frustrating on zuk, not being able to see when jad / healers will spawn was a pain.. lol 

![Leviathan](https://github.com/user-attachments/assets/c8ef3c70-b1bf-451a-82a4-401e8e6d8240)
![Zuk](https://github.com/user-attachments/assets/70f84861-a999-4f63-ad97-419c5e595784)

**Comment by NuclearRalph** [comment]
It just gets frozen at 100... any fixes?

**Comment by xines** [comment]
> It just gets frozen at 100... any fixes?

Not all NPC's support fetching the **Numeric Health** option, so you might want to disable it, hope it helps. :)
