### ISSUE TITLE
More accurate selection

### ISSUE THREAD

**Issue by Kwazix** [lejeffe/MonsterHP#37]
Is it possible to have a click box to only display the HP On/Above enemies that actually have a health bar or enemies you're actively in combat with, As current options are only to have to enter every mob ID in (way to tedious) or have it show for everything, including things like ducks and the waves in zebaks room that dont actually have a hp bar and this is very annoying.

**Comment by lejeffe** [comment]
https://github.com/runelite/plugin-hub/pull/6757 Should be added with the pull request i made to runelite today

**Comment by Kwazix** [comment]
What was added, nothing has changed.

**Comment by xines** [comment]
> What was added, nothing has changed.

@lejeffe Accidentally merged a older pull request on top of my latest pull request resulting in the runelite plugin hub not being able to build, fix is to just roll back to my latest pr but it seems like lejeffe is very busy, i pmed him on discord so let's see. :)

**Comment by Kwazix** [comment]
any updates on this?

**Comment by xines** [comment]
> any updates on this?

![hidehpwhenfull](https://github.com/user-attachments/assets/c88323be-a061-4b2b-95c0-a62605bc5b25)

^ Yes this was added. 😄
