### ISSUE TITLE
Monster HP not updating

### ISSUE THREAD

**Issue by FrozenPoet** [lejeffe/MonsterHP#4]
Monster HP stays at 100% regardless of damage dealt.
Installed / Uninstalled multiple times, reset the plugin multiple times and even reset my settings.prop file.

**Comment by FrozenPoet** [comment]
![Uploading 228f7245e4d9d5ba5b287847360f4899.png…]()

**Comment by FrozenPoet** [comment]
![228f7245e4d9d5ba5b287847360f4899](https://user-images.githubusercontent.com/2621993/189476770-f36a41f7-1460-4724-a8eb-b03ac1287a99.png)

**Comment by lejeffe** [comment]
Does the same thing happen on all monster for you or only a few specific ones?

**Comment by FrozenPoet** [comment]
> 

All of them :(

**Comment by lejeffe** [comment]
Weird as i and others have been using it without much problems. Can you send a screenshot of the plugin settings?

**Comment by FrozenPoet** [comment]
I have used it without any issues the first day I installed it.
On the second day it stopped working and have not been able to get it to work since.

![pluginsettings](https://user-images.githubusercontent.com/2621993/189518537-48cc95e9-330c-4e7a-be1a-bbfc8b3c412a.PNG)

**Comment by lejeffe** [comment]
https://i.imgur.com/JbZPPGD.png

Can you check if it works with these 2 options on?

**Comment by FrozenPoet** [comment]
![newsettings](https://user-images.githubusercontent.com/2621993/189538173-1a0b3310-9397-41c7-b483-2500933ee613.png)
Unfortunately did not fix it :(

**Comment by lejeffe** [comment]
Only difference i see between your and mine setting is the ","after zombie

**Comment by lejeffe** [comment]
Might have a temporary fix, Could you play(enable/disable plugin, change settings) within the "opponent information" plugin
![image](https://user-images.githubusercontent.com/23167100/190838991-9f6d90fc-fc29-4dd0-b26e-b6fda295e0bb.png)

**Comment by dave01233** [comment]
any fix for this yet, im still having the same issue?

**Comment by cigahimbtw** [comment]
Experiencing the same issue. Worked for a Buddy of mine when he copied my exact same settings. I assume another plugin is interfering? 
![image](https://user-images.githubusercontent.com/116535370/197442555-6df3b15a-37a3-4976-8264-7cb1b7863ead.png)

**Comment by AbusiveTuna** [comment]
Let me know if anyone else is having this issue/has resolved this issue. Have been unable to recreate it or solve it.

**Comment by Viskra** [comment]
Was able to fix this issue by uninstalling the "Dude, Where's My Stuff?" plugin by Thource.

**Comment by AbusiveTuna** [comment]
> Was able to fix this issue by uninstalling the "Dude, Where's My Stuff?" plugin by Thource.

That worked for two separate people who were having this issue. Thanks! 

I left an issue on the other plugin: https://github.com/Thource/dude-wheres-my-stuff/issues/47

**Comment by cigahimbtw** [comment]
> 

Confirmed working for me now! Thank you very much! Turning off that plugin fixed it.
