### ISSUE TITLE
Overlay underneath boss

### ISSUE THREAD

**Issue by Arzbishop** [lejeffe/MonsterHP#40]
I assume this is due to a conflict with another plugin, but for Ba-Ba the hp percentage is covered by the boss itself
![2024-10-27_14-11-14](https://github.com/user-attachments/assets/8a6ec4b9-1f4e-4482-8c2c-752c5a957ae5)

**Comment by xines** [comment]
@Arzbishop Most certainly another plugin interfering with the overlay priority. 
![ba-ba](https://github.com/user-attachments/assets/06f528cd-ac0c-4af7-a01f-1bf02c079c61)

**Comment by Arzbishop** [comment]
Alright, so after going through my entire plugin list, the incompatible plugin seems to be Target True Tile (https://runelite.net/plugin-hub/show/target-true-tile). I'm not sure if it's possible for these two plugins to be patched to have compatibility, though it would be great to be able to use both.

**Comment by xines** [comment]
Well it it's theoretically possible for me to bump up the overlay priority as of now it is set very low at the default 0.25 in a range from 0-1.

I see that the "target-true-tile" plugin had already lowered their priority from high (0.75) to 0.6.

fix is prolly just setting the priority higher than theirs, but i am not sure what other plugins people have that this change might impact but it's worth a shot i suppose.

**Comment by Notloc** [comment]
For context, the reason I settled on 0.6 as my overlay's priority was to match Improved Tile Indicators, as both it and Target True Tile perform an entity cutout, where we erase everything underneath our target entities.

I figured it's simpler to match the popular plugin's choice and keep this cutout step at a single point in the render pipeline.
So raising your priority above 0.6 would also handle compatibility with Improved Tile Indicators.

**Comment by xines** [comment]
> For context, the reason I settled on 0.6 as my overlay's priority was to match Improved Tile Indicators, as both it and Target True Tile perform an entity cutout, where we erase everything underneath our target entities.
> 
> I figured it's simpler to match the popular plugin's choice and keep this cutout step at a single point in the render pipeline. So raising your priority above 0.6 would also handle compatibility with Improved Tile Indicators.

Thanks for your insight. I will update priority to something like 0.7-0.75 in the next update, i don't expect this to really cause any issues. 👍

**Comment by lejeffe** [comment]
There are more strange behaviors with how plugins are loaded in. I've had similiar issues with the slayer plugin to highlight npc's. Where it would only work after re-enabling the plugin.

**Comment by xines** [comment]
Should be fixed now @Arzbishop let me know if you are able to test.

**Comment by Arzbishop** [comment]
Seems to be working as intended from my tests. Much appreciated for the fix.

**Comment by xines** [comment]
> Seems to be working as intended from my tests. Much appreciated for the fix.

Thanks for testing and glad it worked. 😄👍
