### ISSUE TITLE
Suggestion: Add option to choose NPCs using NPC ID

### ISSUE THREAD

**Issue by robuuuste** [lejeffe/MonsterHP#7]
Hi,

Currently if you want to see the monster hp percentage of a specific NPC it will show it on all NPCs with that name (for example if you want to see it on a specific type of goblin but not all goblins). It would be nice if we could also choose the NPC using their ID so we can be more specific. (similar to how you can highlight NPCs by ID in the Better NPC Highlight plugin)

**Comment by lejeffe** [comment]
It's possible to add, but i don't know where to find the time to add this as it's quite a bit of work

**Comment by lejeffe** [comment]
It's been on my want to add list for a while now.

**Comment by jacobholden** [comment]
Add please :)

**Comment by xines** [comment]
> It's possible to add, but i don't know where to find the time to add this as it's quite a bit of work

Apologize for old post bump, but this never seemed to be added, so i'll try to add this sooner or later.
