### ISSUE TITLE
Empty font name resetting to default "roboto" when restarting RuneLite

### ISSUE THREAD

**Issue by haakonrp** [lejeffe/MonsterHP#8]
I see that expected behaviour for this is to use runescape's default when font is left empty, but it is resetting to "roboto" when RuneLite is restarted.

**Comment by haakonrp** [comment]
Nice plugin btw :)

**Comment by lejeffe** [comment]
I have done a quick check on my side. It seems to also not save an empty name on my side. But this might be because runelite, goes to default setting if a box is left empty.

**Comment by lejeffe** [comment]
https://i.imgur.com/nuyA9tS.png I have added a toggle to enable custom fonts
