### ISSUE TITLE
ToA Boss HP randomly flicking to 100

### ISSUE THREAD

**Issue by jevonsp** [lejeffe/MonsterHP#9]
I've noticed this definitely on akkha and ba-ba. the hp will randomly flash 100 and then the current hp intermittently. Not sure the cause or if other plugins causing it.

**Comment by lejeffe** [comment]
Might have a temporary fix, Could you play(enable/disable plugin, change settings) within the "opponent information" plugin, my settings for reference
![image](https://user-images.githubusercontent.com/23167100/190838991-9f6d90fc-fc29-4dd0-b26e-b6fda295e0bb.png)

**Comment by jevonsp** [comment]
Tried off/on but cant seem to get anything to fix the issue, sorry :(

**Comment by jevonsp** [comment]
Sorry to bother you, but does this issue show up for you on your side? i

ts slight annoying :(

**Comment by FloppyAl** [comment]
I have the same issue.

**Comment by FloppyAl** [comment]
> Any chance you guys use "Dude, Where's My Stuff?". This seems to cause issues for other people

I don't use that one, never used it before either.

**Comment by jevonsp** [comment]
I don't use it either. It doesnt happen with all mobs either

"ba-ba,akkha,kephri,zebak,warden*, Vorkath" is the string i use, its specifically akkha that does it most noticeably

ive done vork today with no hp flicking

**Comment by lejeffe** [comment]
> 

Akkha happens when it switches attack styles, because technically it becomes another npc with another id. It needs a visible hp bar to update it after it switches attack styles

**Comment by Thource** [comment]
This could be related to #4, that issue isn't specific to `Dude, Where's My Stuff?`.

Any time a config is changed within runelite, for any plugin, this plugin resets the hp. The reason that it's so noticeable with my plugin is that I'm saving something to the config every tick.

This issue will probably also be fixed by #18

**Comment by lejeffe** [comment]
Should be fixed once Runelite approves the update

**Comment by Thource** [comment]
@lejeffe you need to make a PR at https://github.com/runelite/plugin-hub

**Comment by lejeffe** [comment]
> @lejeffe you need to make a PR at https://github.com/runelite/plugin-hub

Already made one a week ago, updated that one to include this fix

**Comment by Thource** [comment]
Ah sorry, only checked recent PRs, thanks!
